name: generic-app
version: 0.0.0

serviceAccount:
  create: false
  # Allow injection annotations required for the vendor to allow API usage (eg: AWS tokens)
  annotations: {}

service:
  create: true

deployment:
  image:
    registry: docker.io
    repository: kennethreitz/httpbin
    # The preference is to always use digest, but tag can still be used if required
    digest:
    tag: latest
  # Optional: specify a custom command for the Docker start
  command: null
  ports:
    - 8080
  # By default it will have Memory QoS guaranteed and burstable CPU (low values so requires adjustment from devs)
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
  env: {}
  # TODO: enforce default values which users can opt-out, instead of being opt-in
  readinessProbe:
  livenessProbe:
  startupProbe:

hpa:
  create: true
  minReplicas: 2
  maxReplicas: 4
  targetCpuUtilization: 70
  targetMemoryUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
